[build]
  publish = "dist/public"
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run vercel-build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION = "false"



